[package]
name = "enlace-testkit"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
async-trait = { workspace = true }
enlace = { path = "../enlace" }
rand = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

[dev-dependencies]
axum-server = { workspace = true }
enlace-relay = { path = "../enlace-relay" }
reqwest = { workspace = true }
