[package]
name = "enlace-testkit"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true
description = "Test transports for enlace."

[features]
default = ["all-transports"]
all-transports = ["http", "dht", "pkarr", "iroh"]
http = ["enlace/http"]
dht = ["enlace/dht"]
pkarr = ["enlace/pkarr"]
iroh = ["enlace/iroh"]

[dependencies]
async-trait = { workspace = true }
enlace = { path = "../enlace", default-features = false }
rand = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
axum-server = { workspace = true }
ed25519-dalek = { workspace = true }
enlace-relay = { path = "../enlace-relay" }
mainline = { workspace = true }
pkarr = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
