[workspace]
resolver = "3"
members = [
    "crates/enlace",
    "crates/enlace-relay",
    "crates/enlace-testkit",
]

[workspace.package]
edition = "2024"
version = "0.1.0"
publish = false

[workspace.dependencies]
async-trait = { version = "=0.1.89" }
tokio = { version = "=1.52.1", default-features = false, features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "io-util",
    "time",
] }
futures-core = { version = "=0.3.32", default-features = false }
chacha20poly1305 = { version = "=0.10.1", default-features = false, features = [
    "std",
    "getrandom",
] }
ed25519-dalek = { version = "=2.2.0", default-features = false, features = [
    "fast",
    "std",
    "zeroize",
] }
hkdf = { version = "=0.12.4", default-features = false }
lru = { version = "=0.18.0", default-features = false }
rand = { version = "=0.10.1" }
sha2 = { version = "=0.10.9", default-features = false }
subtle = { version = "=2.6.1", default-features = false }
tokio-stream = { version = "=0.1.18", default-features = false, features = [
    "sync",
] }
tracing = { version = "=0.1.44", default-features = false }
url = { version = "=2.5.8", default-features = false }
zeroize = { version = "=1.8.2" }
