[package]
name = "enlace-relay"
edition.workspace = true
version.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true
description = "HTTP relay server for enlace."

[[bin]]
name = "enlace-relay"
path = "src/main.rs"

[features]
default = ["tls", "persist"]
tls = ["dep:axum-server", "axum-server/tls-rustls"]
persist = ["dep:sled"]

[dependencies]
anyhow.workspace = true
axum.workspace = true
axum-server = { workspace = true, optional = true }
base64.workspace = true
clap.workspace = true
sled = { workspace = true, optional = true }
tokio.workspace = true

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
