[package]
name = "enlace-relay"
edition.workspace = true
version.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true
description = "HTTP relay server for enlace."

[[bin]]
name = "enlace-relay"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
axum-server.workspace = true
base64.workspace = true
clap.workspace = true
sled.workspace = true
tokio.workspace = true

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
