[package]
name = "enlace"
edition.workspace = true
version.workspace = true
publish.workspace = true

[features]
default = ["iroh"]
fuzzing = []
iroh = ["dep:iroh", "dep:iroh-gossip"]

[dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
chacha20poly1305 = { workspace = true }
ed25519-dalek = { workspace = true }
futures-core = { workspace = true }
hkdf = { workspace = true }
iroh = { workspace = true, optional = true }
iroh-gossip = { workspace = true, optional = true }
lru = { workspace = true }
mainline = { workspace = true }
pkarr = { workspace = true }
rmp-serde = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
x25519-dalek = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
